language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  # not supported by travis: https://github.com/travis-ci/travis-ci/issues/10290 
  # - oraclejdk8
  - oraclejdk9
  - oraclejdk11


